apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: istio-privileged-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-privileged-agent
    release: {{ .Release.Name }}
